[env:esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Native USB CDC serial
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101

lib_deps =
    zinggjm/GxEPD2@^1.6.5
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.16.2
    knolleary/PubSubClient@^2.8
