[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; USB CDC serial (built-in USB on the SuperMini)
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200

lib_deps =
    zinggjm/GxEPD2@^1.6.5
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.16.2
